name: Update Snake

on:
  schedule:
    - cron: '0 0 * * *'  # Chạy mỗi ngày lúc 00:00 UTC
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  update-snake:
    runs-on: ubuntu-latest

    steps:
      # Lấy code từ repo
      - uses: actions/checkout@v2

      # Tạo file con rắn mới
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}  # Lấy username GitHub của repo owner
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Kiểm tra xem file SVG/GIF có được tạo không và commit vào repo
      - name: Commit & Push
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "github-actions[bot]"
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
          message: "Update contribution snake"
          push: true
          branch: main
