name: Update Snake

on:
  schedule:
    - cron: '0 0 * * *'  # Chạy mỗi ngày lúc 00:00 UTC
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  update-snake:
    runs-on: ubuntu-latest

    steps:
      # Lấy code từ repo
      - uses: actions/checkout@v2

      # Tạo file con rắn mới
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: "kietpham-vn"  # Thay username GitHub của bạn
          args: "-p"  # Tạo con rắn

      # Kiểm tra sự tồn tại của file SVG
      - name: Check for generated snake SVG
        run: |
          echo "Checking if the snake file exists..."
          ls -alh # Liệt kê các file trong thư mục làm việc
          if [ ! -f "github-contribution-grid-snake.svg" ]; then
            echo "SVG file not found!"
            exit 1
          fi

      # Commit và push file SVG vào repo
      - name: Commit & Push
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "github-actions[bot]"
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
          message: "Update contribution graph"
          push: true
          branch: main
