name: Update Snake

on:
  schedule:
    - cron: '0 0 * * *'  # Chạy mỗi ngày lúc 00:00 UTC
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  update-snake:
    runs-on: ubuntu-latest

    steps:
      # Lấy code từ repo
      - uses: actions/checkout@v2

      # Tạo file con rắn mới
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: "kietpham-vn"  # Thay thành username GitHub của bạn
          args: "-p"  # Tạo con rắn

      # Kiểm tra sự tồn tại của file SVG
      - name: Check for generated snake SVG
        run: |
          echo "Checking if the snake file exists..."
          ls -alh  # Liệt kê các file trong thư mục làm việc
          if [ ! -f "github-contribution-grid-snake.svg" ]; then
            echo "SVG file not found!"
            exit 1
          fi

      # Sử dụng environment files để set output và commit
      - name: Commit & Push
        run: |
          # Commit lại file SVG vào repo
          echo "example=github-contribution-grid-snake.svg" >> $GITHUB_OUTPUT
          git add github-contribution-grid-snake.svg
          git commit -m "Update contribution graph"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token cần thiết để commit và push

