name: Update Snake

on:
  # Để chạy tự động mỗi ngày
  schedule:
    - cron: '0 0 * * *'  # Thời gian chạy cron (00:00 UTC mỗi ngày)
  # Để có thể chạy thủ công
  workflow_dispatch:   # Thêm sự kiện để bạn có thể chạy thủ công từ GitHub UI

jobs:
  update-snake:
    runs-on: ubuntu-latest

    steps:
      # Lấy code từ repo
      - uses: actions/checkout@v2

      # Tạo file con rắn mới
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user: "kietpham-vn"  # Đổi thành username của bạn
          svg_out_path: "github-contribution-grid-snake.svg"

      # Commit lại file SVG mới vào repo
      - name: Commit & Push
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "github-actions[bot]"
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
          message: "Update contribution graph"
